"""Shareable markdown report (safe to paste into a ticket / Discord / DM).

All secrets are redacted and the hotkey is already masked on the report, so the
output is safe to share when asking for help.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from du_doctor.models import CheckCategory, CheckResult, DoctorReport
from du_doctor.utils.formatting import status_label
from du_doctor.utils.redact import redact_secrets

DEFAULT_REPORT_PATH = "du-doctor-report.md"

# Detailed section ordering + human titles.
_SECTION_ORDER: list[tuple[CheckCategory, str]] = [
    (CheckCategory.SYSTEM, "System"),
    (CheckCategory.BITTENSOR, "Bittensor registration & miner metrics"),
    (CheckCategory.REPO, "Repo / code status"),
    (CheckCategory.PROCESS, "PM2 / process status"),
    (CheckCategory.NETWORK, "Network / axon"),
    (CheckCategory.DATA_UNIVERSE_CONFIG, "Data Universe scraping config"),
    (CheckCategory.DATA_UNIVERSE_DATA, "Data freshness / local DB"),
    (CheckCategory.LOGS, "Logs"),
    (CheckCategory.DATA_UNIVERSE_SCORING, "Earning heuristics (possible reasons)"),
]


def _fmt_time(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def render_markdown(report: DoctorReport) -> str:
    lines: list[str] = []
    lines.append("# Data Universe Miner Doctor Report")
    lines.append("")
    lines.append(
        f"- **Overall status:** {status_label(report.overall_status)} "
        f"{report.overall_status.value}"
    )
    lines.append(f"- **Subnet:** {report.subnet_name} (NETUID {report.netuid})")
    lines.append(f"- **Network:** {report.network}")
    lines.append(f"- **Hotkey:** {report.hotkey_masked or 'not resolved'}")
    lines.append(f"- **Created:** {_fmt_time(report.created_at)}")
    lines.append("")

    # Summary table.
    lines.append("## Summary")
    lines.append("")
    lines.append("| Status | Category | Check | Summary |")
    lines.append("| --- | --- | --- | --- |")
    for c in report.checks:
        summary = redact_secrets(c.summary).replace("|", "\\|")
        lines.append(
            f"| {status_label(c.status)} | {c.category.value} | " f"{c.title} | {summary} |"
        )
    lines.append("")

    # Detailed sections.
    lines.append("## Detailed checks")
    lines.append("")
    by_cat: dict[CheckCategory, list[CheckResult]] = {}
    for c in report.checks:
        by_cat.setdefault(c.category, []).append(c)

    for category, title in _SECTION_ORDER:
        checks = by_cat.get(category)
        if not checks:
            continue
        lines.append(f"### {title}")
        lines.append("")
        for c in checks:
            lines.append(f"**{status_label(c.status)} {c.title}** — {redact_secrets(c.summary)}")
            if c.evidence:
                lines.append("")
                lines.append("```")
                for ev in c.evidence:
                    lines.append(redact_secrets(ev))
                lines.append("```")
            if c.suggested_fixes:
                lines.append("")
                for fix in c.suggested_fixes:
                    lines.append(f"- {redact_secrets(fix)}")
            lines.append("")

    # Suggested fix order.
    lines.append("## Suggested fixes (in priority order)")
    lines.append("")
    if report.suggested_fix_order:
        for i, fix in enumerate(report.suggested_fix_order, start=1):
            lines.append(f"{i}. {redact_secrets(fix)}")
    else:
        lines.append("_No prioritized fixes — nothing critical detected._")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by Data Universe Miner Doctor (read-only). " "Secrets redacted; hotkey masked._"
    )
    return "\n".join(lines)


def write_markdown(report: DoctorReport, path: str | Path = DEFAULT_REPORT_PATH) -> Path:
    """Write the markdown report to disk and return the path."""
    out = Path(path)
    out.write_text(render_markdown(report), encoding="utf-8")
    return out
